name: Deploy to cloudflare workers

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: false
            - name: Install dependencies for migration
              run: pnpm install -g drizzle-orm drizzle-kit postgres tsx
            - name: Apply migrations
              run: pnpm db:migrate
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }} # DATABASE_URL for the main branch
            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v3
              with:
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}


