name: Deploy to cloudflare workers

on:
    push:
        branches:
            - main

jobs:
    migrate:
        runs-on: ubuntu-latest
        name: Migrate
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
                  run_install: false
            - name: Install dependencies for migration
              run: pnpm install -g drizzle-orm drizzle-kit postgres tsx dotenv
            - name: Apply migrations
              run: pnpm db:migrate
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }} # DATABASE_URL for the main branch


